Repository amit-99/SE_Project2, pull requests merged in 2023-10, with the labels that each got.

#9 Merging the updated relative paths for product analysis functionality.
  Amazon_Comments_Scrapper/amazon_reviews_scraping/amazon_reviews_scraping/secret.py
  Amazon_Comments_Scrapper/amazon_reviews_scraping/amazon_reviews_scraping/spiders/ProductAnalysis.txt
  Amazon_Comments_Scrapper/amazon_reviews_scraping/amazon_reviews_scraping/spiders/__pycache__/amazon_review.cpython-311.pyc
  Amazon_Comments_Scrapper/amazon_reviews_scraping/amazon_reviews_scraping/spiders/amazon_review.py
  Amazon_Comments_Scrapper/amazon_reviews_scraping/amazon_reviews_scraping/spiders/reviews.json
  sentimental_analysis/realworld/__pycache__/__init__.cpython-311.pyc
  sentimental_analysis/realworld/__pycache__/admin.cpython-311.pyc
  sentimental_analysis/realworld/__pycache__/apps.cpython-311.pyc
  sentimental_analysis/realworld/__pycache__/models.cpython-311.pyc
  sentimental_analysis/realworld/__pycache__/utilityFunctions.cpython-311.pyc
  sentimental_analysis/realworld/__pycache__/views.cpython-311.pyc
  sentimental_analysis/realworld/migrations/__pycache__/__init__.cpython-311.pyc
  sentimental_analysis/realworld/static/css/namari-color.css
  sentimental_analysis/realworld/static/images/banner-images/banner-image-2.jpg
  sentimental_analysis/realworld/templates/realworld/index.html
  sentimental_analysis/realworld/views.py
  sentimental_analysis/sentimental_analysis/__pycache__/__init__.cpython-311.pyc
  sentimental_analysis/sentimental_analysis/__pycache__/settings.cpython-311.pyc
  sentimental_analysis/sentimental_analysis/__pycache__/urls.cpython-311.pyc
  sentimental_analysis/sentimental_analysis/__pycache__/wsgi.cpython-311.pyc
Labels: bug, enhancement

#10 Added 2 Python liabraries required for web-scrapping.
  requirements.txt
Labels: enhancement

#16 adding badges, workflow, dependencies
  .github/workflows/main.yml
  .pylintrc
  .travis.yml
  Amazon_Comments_Scrapper/amazon_reviews_scraping/amazon_reviews_scraping/settings.py
  Amazon_Comments_Scrapper/amazon_reviews_scraping/amazon_reviews_scraping/spiders/amazon_review.py
  README.md
  requirements.txt
  test/test_sentiment_analysis.py
Labels: documentation

#17 release master for development activity
  .github/workflows/main.yml
  .pylintrc
  .travis.yml
  Amazon_Comments_Scrapper/amazon_reviews_scraping/amazon_reviews_scraping/settings.py
  Amazon_Comments_Scrapper/amazon_reviews_scraping/amazon_reviews_scraping/spiders/amazon_review.py
  README.md
  requirements.txt
  test/test_sentiment_analysis.py
Labels: bug, documentation, enhancement

#19 Fixed functional testing scripts for the features and ensured all test cases were passed for all the respective features.
  Amazon_Comments_Scrapper/amazon_reviews_scraping/amazon_reviews_scraping/spiders/__pycache__/amazon_review.cpython-311.pyc
  sentimental_analysis/realworld/Output.txt
  sentimental_analysis/realworld/__pycache__/amazon_test.cpython-311.pyc
  sentimental_analysis/realworld/functional_testing.py
Labels: bug

#20 tests and linting updation
  .github/workflows/main.yml
  .pylintrc
  .travis.yml
  Amazon_Comments_Scrapper/amazon_reviews_scraping/amazon_reviews_scraping/spiders/amazon_review.py
  sentimental_analysis/__init__.py
  sentimental_analysis/audio/__pycache__/audio_analyzer.cpython-311.pyc
  sentimental_analysis/audio/audio_analyzer.py
  sentimental_analysis/audio/test_AudioAnalyzer.py
  sentimental_analysis/realworld/__pycache__/amazon_test.cpython-311.pyc
  sentimental_analysis/realworld/__pycache__/utilityFunctions.cpython-311.pyc
  sentimental_analysis/realworld/admin.py
  sentimental_analysis/realworld/amazon_test.py
  sentimental_analysis/realworld/functional_testing.py
  sentimental_analysis/realworld/models.py
  sentimental_analysis/realworld/newsScraper.py
  sentimental_analysis/realworld/tests.py
  sentimental_analysis/realworld/utilityFunctions.py
  sentimental_analysis/realworld/views.py
  sentimental_analysis/sentimental_analysis/settings.py
  sentimental_analysis/sentimental_analysis/urls.py
  test/__pycache__/all_functionality_testing.cpython-311-pytest-7.4.2.pyc
  test/__pycache__/test_all_functionality.cpython-311-pytest-7.4.2.pyc
  test/__pycache__/test_audio_sentiment_analysis.cpython-311-pytest-7.4.2.pyc
  test/__pycache__/test_sentiment_analysis.cpython-311-pytest-7.4.2.pyc
  test/test_all_functionality.py
  test/test_audio_sentiment_analysis.py
Labels: documentation

#28 Community support block to read me
  README.md
Labels: documentation, enhancement
